//// Thank you: https://discord.com/channels/686053708261228577/840286264964022302/877506735856836661
//const { build } = require("esbuild");
//
//const banner = `/*
//THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
//If you want to view the source, visit the plugins’ github repository.
//*/
//`;
//
//const fs = require("fs");
//
//const copyManifest = {
//  name: "copy-manifest",
//  setup: (build) => {
//    build.onEnd(() => {
//      fs.copyFileSync("manifest.json", "build/manifest.json");
//    });
//  },
//};
//
//const isProd = process.env.BUILD === "production";
//
//(async () => {
//  try {
//    await build({
//      entryPoints: ["src/main.ts"],
//      bundle: true,
//      watch: !isProd,
//      platform: "node",
//      external: ["obsidian"],
//      format: "cjs",
//      //mainFields: ["browser", "module", "main"],
//      banner: { js: banner },
//      sourcemap: isProd ? false : "inline",
//      minify: isProd,
//      treeShaking: true,
//      define: {
//        "process.env.NODE_ENV": JSON.stringify(process.env.BUILD),
//      },
//      outfile: "build/main.js",
//      //outdir: "build/",
//      plugins: [
//        copyManifest,
//      ],
//    });
//  } catch (err) {
//    console.error(err);
//    process.exit(1);
//  }
//})();

import esbuild from "esbuild";
import process from "process";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    minify: false,
    watch: true,
    logLevel: "info",
    treeShaking: true,
    outdir: 'build/',
}).catch(() => process.exit(1));